name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov requests codecov

      - name: Lint code
        run: flake8 app/

      - name: Run tests & generate coverage report
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --cov=app --cov-branch --cov-report=term-missing --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t hello-docker-app:ci .

      - name: Smoke test container
        run: |
          docker run -d -p 8080:8080 --name testci hello-docker-app:ci
          sleep 5
          curl --fail http://localhost:8080
          docker rm -f testci

      - name: Tag & push Docker image
        run: |
          docker tag hello-docker-app:ci ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker-app:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker-app:${{ github.sha }}
