name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install flake8 pytest pytest-cov requests

      - name: Lint code
        run: flake8 app/

      - name: Run tests with coverage
        run: |
          export PYTHONPATH="${{ github.workspace }}"
          pytest --cov=app --cov-report=term-missing

      - name: Build Docker image
        run: docker build -t hello-docker-app:ci .

      - name: Smoke test container
        run: |
          docker run -d -p 8080:8080 --name testci hello-docker-app:ci
          sleep 5
          curl --fail http://localhost:8080
          docker rm -f testci
